---
title: "Compare myeloid/lymphoid marker expression between groups"
author: "heinin"
date: "2024-03-13"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

## Introduction

Plotting various myeloid and lymphoid markers in each treatment group and cell type.

### Packages and environment variables

```{r, warning=F, message=F}

suppressPackageStartupMessages({
  #library(cli)
  library(Seurat)
  library(SeuratObject)
  library(SeuratDisk)
  library(tidyverse)
  library(tibble)
  library(ggplot2)
  library(ggpubr)
  library(ggrepel)
  library(workflowr)
  library(googlesheets4)
  library(scProportionTest)})

setwd("/home/hnatri/PD1_mm/")
set.seed(9999)
options(ggrepel.max.overlaps = Inf)

# Colors, themes, cell type markers, and plot functions
source("/home/hnatri/PD1_mm/code/utilities.R")
source("/home/hnatri/PD1_mm/code/PD1_mm_themes.R")
source("/home/hnatri/PD1_mm/code/CART_plot_functions.R")

```

### Importing data

```{r}

seurat_data <- readRDS("/tgen_labs/banovich/BCTCSF/PD1_mm_Seurat/PD1_mm_Seurat_GSEA.Rds")
seurat_data$Treatment_Day <- paste0(seurat_data$Treatment, "_", seurat_data$Day)

# Normalizing all features in the Seurat object for plotting
seurat_data <- NormalizeData(seurat_data, assay = "RNA", verbose = F)
seurat_data <- NormalizeData(seurat_data, assay = "RNA_human", verbose = F)

```

### Exhaustion markers and ENTPD1 (CD39)

```{r, fig.height = 16, fig.width = 9}

# PDCD1 = PD1
# CD244 = 2B4

seurat_data$celltype <- factor(seurat_data$celltype,
                               levels = sort(as.character(unique(seurat_data$celltype))))

VlnPlot(seurat_data,
        features = c("ENTPD1", "TIGIT", "PDCD1", "LAG3", "CD244", "CD160", "CD8A"),
        assay = "RNA_human",
        group.by = "celltype",
        split.by = "Treatment",
        split.plot = T,
        pt.size = 0,
        ncol = 1) &
    theme_classic2() &
    theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))

```

```{r, fig.height = 12}

DotPlot(seurat_data,
        features = c("ENTPD1", "TIGIT", "PDCD1", "LAG3", "CD244", "CD160", "CD8A"),
        assay = "RNA_human",
        group.by = "celltype",
        split.by = "Treatment",
        cols = rep("tomato2", 3)) &
    theme_classic2() &
    theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))

```

### Human T cell canonical markers

```{r, fig.height = 3, fig.width = 9, warning=F, message=F}

# Canonical T cell markers
gs4_deauth()
canonical_markers  <- gs4_get("https://docs.google.com/spreadsheets/d/186PIcU3Jb0Xm3IuZgENEChluykvwsK4JnHF8FbeJASA/edit?usp=sharing")
sheet_names(canonical_markers)
canonical_markers <- read_sheet(canonical_markers, sheet = "T cells, gene sets")
canonical_markers <- unique(canonical_markers$RNA)
canonical_markers <- intersect(canonical_markers, rownames(seurat_data))

lapply(canonical_markers, function(xx){
  VlnPlot(seurat_data,
          features = xx,
          assay = "RNA_human",
          slot = "data",
          group.by = "celltype",
          split.by = "Treatment_Day",
          pt.size = 0,
          ncol = 1) &
    theme_classic2() &
    theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))
})
```

### Myeloid markers

```{r, fig.height = 42, fig.width = 8}

plot_features <- c("MIF", "PDPN", "NLRP3", "IL1B", "S100A8", "S100A9",
                   "S100A10", "TYROBP", "CD68", "ICAM1", "C1QA", "C1QB", "C1QC",
                   "CD74", "AREG", "APOE", "SPP1", "CD274")

# Plotting by cell type
VlnPlot(seurat_data,
        features = sort(plot_features),
        assay = "RNA_human",
        group.by = "celltype",
        pt.size = 0,
        ncol = 1) &
    theme_classic2() &
    NoLegend() &
    theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))

```

```{r, fig.height = 9}
DotPlot(seurat_data,
        features = sort(plot_features),
        assay = "RNA_human",
        group.by = "celltype") &
    theme_classic2() &
    theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))
```

```{r, fig.height = 38, fig.width = 14}

VlnPlot(seurat_data,
        features = sort(plot_features),
        assay = "RNA_human",
        group.by = "celltype",
        split.by = "Treatment_Day",
        pt.size = 0,
        ncol = 1) &
    theme_classic2() &
    theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1)) &
    NoLegend()

```

```{r, fig.height = 34, fig.width = 10}

# Myeloid cells only
VlnPlot(subset(seurat_data, subset = celltype %in% paste0("M", seq(1, 9))),
        features = sort(plot_features),
        assay = "RNA_human",
        group.by = "celltype",
        split.by = "Treatment_Day",
        pt.size = 0,
        ncol = 1) &
    theme_classic2() &
    theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))

```

```{r, fig.height = 10, fig.width = 10}

VlnPlot(subset(seurat_data, subset = celltype %in% paste0("M", seq(1, 9))),
        features = c("SPP1", "C1QA", "C1QB", "C1QC"),
        assay = "RNA_human",
        layer = "data",
        group.by = "celltype",
        split.by = "Treatment_Day",
        pt.size = 0,
        ncol = 1,
        cols = treatment_day_col) &
    theme_classic2() &
    theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))

```

### Plotting SPP1

```{r, fig.height=3}

VlnPlot(subset(seurat_data, subset = celltype %in% paste0("M", seq(1, 9))),
        features = "SPP1",
        group.by = "celltype",
        split.by = "Treatment_Day",
        assay = "RNA_human",
        layer = "data",
        pt.size = 0,
        log = T)

```

### Heatmap of pseudobulk marker expression
